### ISSUE TITLE
[Bug] Application throws Unhandled exception error on exit

### ISSUE THREAD

**Issue by keithgh1** [imqqmi/FloppyControl#1]
When exiting the application using the close window button in the upper right hand corner, this error is thrown each time.

Please see screenshot and full details 

[error_on_exit.txt](https://github.com/imqqmi/FloppyControl/files/4927221/error_on_exit.txt)
![error_on_exit](https://user-images.githubusercontent.com/31483472/87581731-6dab4380-c6a7-11ea-86b7-35c928102c35.jpg)

attached.

System.IO.FileLoadException: Could not load file or assembly 'NationalInstruments.Common, Version=13.0.40.168, Culture=neutral, PublicKeyToken=dc6ad606294fc298' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'NationalInstruments.Common, Version=13.0.40.168, Culture=neutral, PublicKeyToken=dc6ad606294fc298'
   at FloppyControlApp.connectsocketNIVisa2.Disconnect()
   at FloppyControlApp.FloppyControl.Dispose(Boolean disposing)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by keithgh1** [comment]
Environment is Windows 10 Pro Build 19041.388

**Comment by imqqmi** [comment]
This is because the National Instruments driver isn't installed for the oscilloscope (Rigol DS1054Z).  In commit cf077a9 it catches the exception for those that don't need/use the driver.
