### ISSUE TITLE
[Bug] Unhandled IndexOutofRangeException thrown on SCP file import

### ISSUE THREAD

**Issue by keithgh1** [imqqmi/FloppyControl#2]
On every(?) SCP file import, an Unhandled IndexOutofRangeException is thrown. I am testing SCP files generated from SuperCard Pro Disk Archiver 2.20.

[unhandled_IndexOutofRange.txt](https://github.com/imqqmi/FloppyControl/files/4969399/unhandled_IndexOutofRange.txt)

![scp_load_exception](https://user-images.githubusercontent.com/31483472/88345335-c320c980-cd13-11ea-9a4f-e29137e8ff2e.jpg)

**Comment by keithgh1** [comment]
Windows 10 pro 10.0.19041

**Comment by imqqmi** [comment]
Check, I've fixed the issue in commit 78a4ac3.
