### ISSUE TITLE
[Enhancement] Add a way to reset the application to initial state

### ISSUE THREAD

**Issue by keithgh1** [imqqmi/FloppyControl#3]
Whether it's via a "New" option under file or some other manner, there are so many options, the application can get into an odd state, and the only current way is to simply exit the app (which is currently throwing an exception) and start over.

**Comment by imqqmi** [comment]
There's a reset input and a reset output buttons on the Processing tab which tries to do just that. Reset input erases the input raw flux data, reset output resets the sector data that was recovered in case you want to start over but want to keep the current flux data.
